spring:
  application:
    name: spring-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation_project?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    static-path-pattern: /**
server:
  port: 10001
eureka:
  client:
    service-url:
      defaultZone : http://localhost:10000/eureka/